language: cpp

matrix:
  fast_finish: true
  include:
  - name: Ubuntu release
    os: linux
    dist: xenial
    group: stable
    compiler: clang
    addons:
      apt:
        sources:
        - sourceline: 'ppa:beineri/opt-qt-5.12.0-xenial'
        update: true
        packages:
        - qt512base
        - qt512tools
        - qt512x11extras
        - libgl1-mesa-dev
    install:
      - wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
      - sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-xenial.list http://packages.lunarg.com/vulkan/lunarg-vulkan-xenial.list
      - sudo apt update
      - sudo apt install vulkan-sdk
    script:
      - PATH="/opt/qt512/bin:$PATH"
      - CXX="clang++"
      - qt512-env.sh
      - qmake CONFIG+=release PREFIX=/usr
      - make INSTALL_ROOT=appdir install ; find appdir/
      - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
      - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
      # export VERSION=... # linuxdeployqt uses this for naming the file
      - cp vulkanCapsViewer.png appdir/usr/share/icons/hicolor/256x256/apps/vulkanCapsViewer.png
      - ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/* -appimage
  deploy:
    provider: script
    script: bash redist/deploy_latest.sh
    on:
      branch: master
      tags: false