language: cpp

matrix:
  fast_finish: true
  include:
  - name: Ubuntu release
    os: linux
    dist: xenial
    group: stable
    compiler: clang
    addons:
      apt:
        sources:
        - sourceline: 'ppa:beineri/opt-qt-5.12.0-xenial'
        update: true
        packages:
        - qt512base
        - qt512tools
        - qt512x11extras
        - libgl1-mesa-dev
    install:
      - wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
      - sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-xenial.list http://packages.lunarg.com/vulkan/lunarg-vulkan-xenial.list
      - sudo apt update
      - sudo apt install vulkan-sdk
    script:
      - PATH="/opt/qt512/bin:$PATH"
      - CXX="clang++"
      - qt512-env.sh
      - qmake CONFIG+=release PREFIX=/usr
      - make INSTALL_ROOT=appdir install ; find appdir/
      # - curl -T appdir/usr/local/bin/vulkanCapsViewer -u ${ftp_user}:${ftp_pass} ftp://ftp.delphigl.de
      - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
      - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
      # export VERSION=... # linuxdeployqt uses this for naming the file
      - cp appdir/usr/local/bin/vulkanCapsViewer appdir/usr/bin/vulkanCapsViewer
      - cp vulkanCapsViewer.png appdir/usr/share/icons/hicolor/256x256/apps/vulkanCapsViewer.png
      - ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/* -appimage
    after_success:
      - curl -T /usr/local/bin/vulkanCapsViewer*.AppImage -u ${ftp_user}:${ftp_pass} ftp://ftp.delphigl.de  
      # find appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq # for debugging
      # curl --upload-file APPNAME*.AppImage https://transfer.sh/APPNAME-git.$(git rev-parse --short HEAD)-x86_64.AppImage
      # - curl -T /usr/local/bin/vulkanCapsViewer -u ${ftp_user}:${ftp_pass} ftp://ftp.delphigl.de   appdir/usr/local/bin/vulkanCapsViewer
      - # Generate AppImage
      # - sudo apt-get -y install checkinstall
      # - sudo checkinstall --pkgname=app --pkgversion="1" --pkgrelease="1" --backup=no --fstrans=no --default --deldoc
      # - mkdir -p appdir/usr/bin ; cd appdir
      # - dpkg -x ../app_1-1_amd64.deb . ; find .
      #- mv ./usr/local/bin/* ./usr/bin/ 
      # - cp ./usr/share/icons/hicolor/48x48/apps/YOUR_APP_ICON.png .
      # - cp ./usr/share/applications/vulkanCapsViewer.desktop .
      #- cd ..
      # - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
      # - chmod a+x linuxdeployqt*.AppImage
      # - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
      # - ./linuxdeployqt*.AppImage /usr/local/bin/* -bundle-non-qt-libs
      # - ./linuxdeployqt*.AppImage /usr/local/bin/* -appimage
      # - curl --ftp-create-dirs
      #   -T ./Vulkan*.AppImage
      #   sftp://${ftp_user}:${ftp_pass}@delphigl.de